spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.134.87.155:3306/Xiaomi_mnd?rewriteBatchedStatements=true
      username: root
      password: 6579927
  redis:
    host: 8.134.87.155
    port: 6379
    password: 6579927
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  rabbitmq:
    port: 5672
    host: 8.134.87.155
    username: admin
    password: admin
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: /xiaomi
    listener:
      direct:
        acknowledge-mode: auto
  #    #这个配置是保证消费者会消费消息，手动确认
#    listener:
#      simple:
#        acknowledge-mode: manual
#    template:
#      mandatory: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
minio:
  endpoint: http://8.134.87.155:9090
  accessKey: admin
  secretKey: 12345678
  bucketName: myblog